# Generated by Django 6.1 on 2026-08-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_phonenumber_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
