# Generated by Django 6.1 on 2026-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_phonenumber_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
