# Generated by Django 6.1 on 2026-09-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobiles'), ('tv', 'TV'), ('led', 'LED'), ('laptop', 'Laptops'), ('electronics', 'Electronics'), ('shoes', 'Shoes'), ('fashion', 'Fashion'), ('accessories', 'Accessories')], default='mobile', max_length=30),
            preserve_default=False,
        ),
    ]
