# Generated by Django 6.1 on 2026-09-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0017_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='otp_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='otp_resend_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
