# Generated by Django 6.1 on 2026-09-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0018_phonenumber_otp_last_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='otp_limit_reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
